import { CommonProps } from "@mui/material/OverridableComponent";

import { colors } from "../../../assets/colors";
export const styles: Record<string, CommonProps["style"]> = {
  root: {},
  tableScrollableWrapper: {
    minWidth: 1200,
    borderRadius: 8,
    border: "1px solid #B8E0D2",
  },
  tableContainer: {
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
  },
  table: {
    display: "flex",
    flexDirection: "column",
    overflowY: "hidden",
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
  },
  headerSideCell: {
    fontWeight: "bold",
    width: 150,
    minWidth: 150,
    maxWidth: 150,
    padding: "2px 4px",
    flex: 1,
    fontSize: 10,
    borderBottom: `1px solid ${colors.powderBlue}`,
    borderRight: `1px solid ${colors.powderBlue}`,
    display: "flex",
    backgroundColor: colors.vistaBlue,
    alignItems: "center",
  },
  tableRow: {
    display: "flex",
    flexDirection: "row",
    height: 30,
  },
  totalCell: {
    width: 150,
    minWidth: 150,
    maxWidth: 150,
    borderRight: `1px solid ${colors.powderBlue}`,
    flexDirection: "row",
    borderBottom: `1px solid ${colors.powderBlue}`,
    display: "flex",
    textAlign: "start",
    alignItems: "center",
    fontWeight: "bold",
    padding: 4,
    backgroundColor: colors.vistaBlue,
  },
  headerTableCell: {
    width: 150,
    minWidth: 150,
    maxWidth: 150,
    padding: "2px 4px",
    flex: 1,
    fontSize: 10,
    borderBottom: `1px solid ${colors.vistaBlue}`,
    borderRight: `1px solid ${colors.vistaBlue}`,
    display: "flex",
    backgroundColor: colors.powderBlue,
    alignItems: "center",
  },
  headerTableCellText: {
    fontSize: 10,
    cursor: "pointer",
  },
  headerCheckboxCell: {
    width: 150,
    minWidth: 150,
    maxWidth: 150,
    padding: "2px 4px",
    flex: 1,
    borderBottom: `1px solid ${colors.vistaBlue}`,
    borderRight: `1px solid ${colors.vistaBlue}`,
    backgroundColor: colors.powderBlue,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 16,
  },
  tableCell: {
    width: 150,
    minWidth: 150,
    maxWidth: 150,
    borderRight: `1px solid ${colors.vistaBlue}`,
    flexDirection: "row",
    borderBottom: `1px solid ${colors.vistaBlue}`,
    display: "flex",
    textAlign: "start",
    justifyContent: "flex-start",
    alignItems: "center",
    padding: 4,
  },
  tableRowOverview: {
    display: "flex",
  },
  tableHeader: {
    width: "calc(100vw - 10rem)",
    padding: "1rem",
    backgroundColor: `${colors.vistaBlue}`,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottom: `2px solid ${colors.tifanyBlue}`,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
  },
  tableTitle: {
    fontSize: 20,
    fontWeight: "bold",
  },
  selectedRow: {
    backgroundColor: colors.fairyTale,
  },
};
